"use client";

import { ArrowRight } from "@phosphor-icons/react";
import { useEffect } from "react";
import { BODIES, TOUR_SECTIONS, type BodyId, type SectionId } from "@/data/bodies";
import { frame } from "@/lib/frame";
import { scrollToSection } from "@/lib/scroll";
import { useApp } from "@/lib/store";
import { StoryPanel } from "./StoryPanel";

const sectionDomId = (id: SectionId) => `section-${id}`;

function measure() {
  frame.tops = TOUR_SECTIONS.map((id) => {
    const el = document.getElementById(sectionDomId(id));
    return el ? el.getBoundingClientRect().top + window.scrollY : 0;
  });
}

export function Tour() {
  const mode = useApp((s) => s.mode);
  const activeSection = useApp((s) => s.activeSection);
  const flying = useApp((s) => s.flying);
  const reducedMotion = useApp((s) => s.reducedMotion);
  const enterExplore = useApp((s) => s.enterExplore);

  useEffect(() => {
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(document.body);
    window.addEventListener("resize", measure);
    return () => {
      ro.disconnect();
      window.removeEventListener("resize", measure);
    };
  }, []);

  const shown = (index: number) => activeSection === index && !flying;

  return (
    <main className="tour" data-mode={mode} inert={mode === "explore" || undefined}>
      <section id={sectionDomId("hero")} className="tour-section" data-shown={shown(0)}>
        <div className="tour-sticky hero-sticky" data-side="left">
          <div className="hero-copy">
            <h1 className="hero-title">
              A star, eight planets,
              <br />
              and the dark between.
            </h1>
            <p className="hero-sub">
              Scroll to fly outward from the Sun, or take the controls and roam the system yourself.
            </p>
            <div className="hero-actions">
              <button type="button" className="pill pill-primary" onClick={() => scrollToSection(1, reducedMotion)}>
                Begin the tour
                <span className="pill-icon">
                  <ArrowRight size={14} weight="light" />
                </span>
              </button>
              <button type="button" className="pill" onClick={() => enterExplore(null)}>
                Explore
              </button>
            </div>
          </div>
        </div>
      </section>

      {TOUR_SECTIONS.map((id, index) => {
        if (id === "hero" || id === "outro") return null;
        const body = BODIES[id as BodyId];
        const side = body.framing.side > 0 ? "right" : "left";
        return (
          <section key={id} id={sectionDomId(id)} className="tour-section" data-shown={shown(index)}>
            <div className="tour-sticky" data-side={side}>
              <StoryPanel body={body} onExplore={() => enterExplore(body.id)} onSelect={(id) => enterExplore(id)} />
            </div>
          </section>
        );
      })}

      <section id={sectionDomId("outro")} className="tour-section" data-shown={shown(TOUR_SECTIONS.length - 1)}>
        <div className="tour-sticky" data-side="center">
          <div className="outro-copy">
            <h2 className="outro-title">Nothing here is to scale.</h2>
            <p className="outro-body">
              At true scale Neptune would sit thirty times farther from the Sun than Earth, and every planet would
              shrink to a dot. This model squeezes the distances and enlarges the worlds so you can see them together.
            </p>
            <div className="outro-actions">
              <button type="button" className="pill pill-primary" onClick={() => enterExplore(null)}>
                Explore
                <span className="pill-icon">
                  <ArrowRight size={14} weight="light" />
                </span>
              </button>
              <button type="button" className="pill" onClick={() => scrollToSection(0, reducedMotion)}>
                Back to the Sun
              </button>
            </div>
            <p className="credits">
              Figures follow NASA planetary fact sheets. Every surface is generated by a shader; nothing is a
              photograph. Built with Next.js and Three.js.
            </p>
          </div>
        </div>
      </section>
    </main>
  );
}
